---
# tasks file for sbaerlocher.cloud

- name: show all cloudscale server
  uri:
    url: https://api.cloudscale.ch/v1/servers
    method: GET
    headers:
      Authorization: "Bearer {{ cloud_cloudscale_api_key }}"
      Content-Type: "application/json"
  register: cloudscale_server_list

- name: init empty vars
  set_fact:
    cloud_cloudscale_server_list: "[]"
    cloud_cloudscale_new_server: "[]"

- name: all cloudscale server
  set_fact:
    cloud_cloudscale_server_list: "{{ cloud_cloudscale_server_list }} + [ '{{ item.name }}' ]"
  with_items:
    - "{{ cloudscale_server_list.json }}"

- name: all new server
  set_fact:
    cloud_cloudscale_new_server: "{{ cloud_cloudscale_new_server }} + [ '{{ item }}' ]"
  with_items:
    - "{{ groups['all'] }}"
  when: item not in cloud_cloudscale_server_list

- name: start cloudscale server
  cloudscale_server:
    name: "{{ item }}"
    image: ubuntu-16.04
    flavor: flex-2
    ssh_keys: "{{ cloud_ssh_public_key_root }}"
    use_public_network: true
    use_private_network: true
    volume_size_gb: 10
    api_token: "{{ cloud_cloudscale_api_key }}"
    user_data: |
      "{{ cloud_cloud_init }}"
      runcmd:
        - "ln -sf /usr/bin/python2.7 /usr/bin/python"
      package_reboot_if_required: true
  with_items:
    - "{{ cloud_cloudscale_new_server }}"
