---
# tasks file for sbaerlocher.cloud

- name: show all cloudscale server
  uri:
    url: https://api.cloudscale.ch/v1/servers
    method: GET
    headers:
      Authorization: "Bearer {{ cloud_cloudscale_api_key }}"
      Content-Type: "application/json"
  register: cloudscale_server_list

- name: init empty vars
  set_fact:
    cloud_cloudscale_server_list: "[]"
    cloud_cloudscale_new_server: "[]"

- name: all cloudscale server
  no_log: true
  set_fact:
    cloud_cloudscale_server_list: "{{ cloud_cloudscale_server_list }} + [ '{{ item.name }}' ]"
  with_items:
    - "{{ cloudscale_server_list.json }}"

- name: all new server
  set_fact:
    cloud_cloudscale_new_server: "{{ cloud_cloudscale_new_server }} + [ '{{ item }}' ]"
  with_items:
    - "{{ groups['all'] }}"
  when: item not in cloud_cloudscale_server_list

- name: start cloudscale server
  cloudscale_server:
    name: "{{ item }}"
    image: "{{ cloud_image }}"
    flavor: "{{ cloud_cloudscale_flavor }}"
    ssh_keys: "{{ cloud_ssh_public_key_root }}"
    use_public_network: "{{ cloud_cloudscale_use_public_network }}"
    use_private_network: "{{ cloud_cloudscale_use_private_network }}"
    volume_size_gb: "{{ cloud_cloudscale_volume_size_gb }}"
    api_token: "{{ cloud_cloudscale_api_key }}"
    user_data: |
      #cloud-config
      users:
        - name: ansible
          passwd: "{{ lookup('password') }}"
          shell: /bin/bash
          primary-group: ansible
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: sudo
          ssh-authorized-keys:
            - "{{ cloud_ssh_public_key_ansible }}"
      package_update: true
      package_upgrade: true
      packages:
        - python2.7
        - python-pip
      write_files:
        - content: |
            auto ens4
            iface ens4 inet static
              address "{{ hostvars[item]['ansible_host'] }}"
              netmask 255.255.255.0
              dns-nameserver 8.8.8.8
              dns-search "{{ cloud_dns_search }}"
              up route add -net 10.16.0.0 netmask 255.240.0.0 gw 172.16.1.1
              up route add -net 172.16.0.0 netmask 255.240.0.0 gw 172.16.1.1
          path: /etc/network/interfaces.d/ens4.cfg
          permissions: 0644
      runcmd:
        - "ln -sf /usr/bin/python2.7 /usr/bin/python"
      package_reboot_if_required: true
  with_items:
    - "{{ cloud_cloudscale_new_server }}"
